# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0263b43205c5dd8f9ab343b23c68c973ee837d36b508d469b836fce5ad1f396ffc3511430376b920d9504c996fe44c8430da8df7f08cc561d27c9689cdcfab87

test:
  secret_key_base: fc9b90f1358df69e22c4bc5d3ef0a0f31e444311a3fb681d237f62fb800ffa5186abd9f43abd5fa9c00a184a0a74f4c1b71d216320022c60afdb4167ada9c1a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
